name: Build docker image and deploy
on:
  push:
    branches:
      - 'dev'

jobs:
  Build-Docker-Image-And-Deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - id: repository_name
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}

      -
        name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        env:
          IMAGE: ${{ steps.repository_name.outputs.lowercase }}
        with:
          push: true
          tags: ghcr.io/${{ env.IMAGE }}:latest
          context: .
          file: ./build_configs/build.dockerfile

      -
        name: Invoke deployment hook
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.WEBHOOK_URL }}